// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.5.0
// source: reference.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ReferenceValueProviderService_QueryReferenceValue_FullMethodName    = "/reference.ReferenceValueProviderService/QueryReferenceValue"
	ReferenceValueProviderService_RegisterReferenceValue_FullMethodName = "/reference.ReferenceValueProviderService/RegisterReferenceValue"
	ReferenceValueProviderService_DeleteReferenceValue_FullMethodName   = "/reference.ReferenceValueProviderService/DeleteReferenceValue"
	ReferenceValueProviderService_SetReferenceValueList_FullMethodName  = "/reference.ReferenceValueProviderService/SetReferenceValueList"
)

// ReferenceValueProviderServiceClient is the client API for ReferenceValueProviderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReferenceValueProviderServiceClient interface {
	QueryReferenceValue(ctx context.Context, in *ReferenceValueQueryRequest, opts ...grpc.CallOption) (*ReferenceValueQueryResponse, error)
	RegisterReferenceValue(ctx context.Context, in *ReferenceValueRegisterRequest, opts ...grpc.CallOption) (*ReferenceValueRegisterResponse, error)
	DeleteReferenceValue(ctx context.Context, in *ReferenceValueDeleteRequest, opts ...grpc.CallOption) (*ReferenceValueDeleteResponse, error)
	SetReferenceValueList(ctx context.Context, in *ReferenceValueListRequest, opts ...grpc.CallOption) (*ReferenceValueListResponse, error)
}

type referenceValueProviderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReferenceValueProviderServiceClient(cc grpc.ClientConnInterface) ReferenceValueProviderServiceClient {
	return &referenceValueProviderServiceClient{cc}
}

func (c *referenceValueProviderServiceClient) QueryReferenceValue(ctx context.Context, in *ReferenceValueQueryRequest, opts ...grpc.CallOption) (*ReferenceValueQueryResponse, error) {
	out := new(ReferenceValueQueryResponse)
	err := c.cc.Invoke(ctx, ReferenceValueProviderService_QueryReferenceValue_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *referenceValueProviderServiceClient) RegisterReferenceValue(ctx context.Context, in *ReferenceValueRegisterRequest, opts ...grpc.CallOption) (*ReferenceValueRegisterResponse, error) {
	out := new(ReferenceValueRegisterResponse)
	err := c.cc.Invoke(ctx, ReferenceValueProviderService_RegisterReferenceValue_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *referenceValueProviderServiceClient) DeleteReferenceValue(ctx context.Context, in *ReferenceValueDeleteRequest, opts ...grpc.CallOption) (*ReferenceValueDeleteResponse, error) {
	out := new(ReferenceValueDeleteResponse)
	err := c.cc.Invoke(ctx, ReferenceValueProviderService_DeleteReferenceValue_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *referenceValueProviderServiceClient) SetReferenceValueList(ctx context.Context, in *ReferenceValueListRequest, opts ...grpc.CallOption) (*ReferenceValueListResponse, error) {
	out := new(ReferenceValueListResponse)
	err := c.cc.Invoke(ctx, ReferenceValueProviderService_SetReferenceValueList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReferenceValueProviderServiceServer is the server API for ReferenceValueProviderService service.
// All implementations must embed UnimplementedReferenceValueProviderServiceServer
// for forward compatibility
type ReferenceValueProviderServiceServer interface {
	QueryReferenceValue(context.Context, *ReferenceValueQueryRequest) (*ReferenceValueQueryResponse, error)
	RegisterReferenceValue(context.Context, *ReferenceValueRegisterRequest) (*ReferenceValueRegisterResponse, error)
	DeleteReferenceValue(context.Context, *ReferenceValueDeleteRequest) (*ReferenceValueDeleteResponse, error)
	SetReferenceValueList(context.Context, *ReferenceValueListRequest) (*ReferenceValueListResponse, error)
	mustEmbedUnimplementedReferenceValueProviderServiceServer()
}

// UnimplementedReferenceValueProviderServiceServer must be embedded to have forward compatible implementations.
type UnimplementedReferenceValueProviderServiceServer struct {
}

func (UnimplementedReferenceValueProviderServiceServer) QueryReferenceValue(context.Context, *ReferenceValueQueryRequest) (*ReferenceValueQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryReferenceValue not implemented")
}
func (UnimplementedReferenceValueProviderServiceServer) RegisterReferenceValue(context.Context, *ReferenceValueRegisterRequest) (*ReferenceValueRegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterReferenceValue not implemented")
}
func (UnimplementedReferenceValueProviderServiceServer) DeleteReferenceValue(context.Context, *ReferenceValueDeleteRequest) (*ReferenceValueDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteReferenceValue not implemented")
}
func (UnimplementedReferenceValueProviderServiceServer) SetReferenceValueList(context.Context, *ReferenceValueListRequest) (*ReferenceValueListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetReferenceValueList not implemented")
}
func (UnimplementedReferenceValueProviderServiceServer) mustEmbedUnimplementedReferenceValueProviderServiceServer() {
}

// UnsafeReferenceValueProviderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReferenceValueProviderServiceServer will
// result in compilation errors.
type UnsafeReferenceValueProviderServiceServer interface {
	mustEmbedUnimplementedReferenceValueProviderServiceServer()
}

func RegisterReferenceValueProviderServiceServer(s grpc.ServiceRegistrar, srv ReferenceValueProviderServiceServer) {
	s.RegisterService(&ReferenceValueProviderService_ServiceDesc, srv)
}

func _ReferenceValueProviderService_QueryReferenceValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReferenceValueQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReferenceValueProviderServiceServer).QueryReferenceValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReferenceValueProviderService_QueryReferenceValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReferenceValueProviderServiceServer).QueryReferenceValue(ctx, req.(*ReferenceValueQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReferenceValueProviderService_RegisterReferenceValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReferenceValueRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReferenceValueProviderServiceServer).RegisterReferenceValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReferenceValueProviderService_RegisterReferenceValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReferenceValueProviderServiceServer).RegisterReferenceValue(ctx, req.(*ReferenceValueRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReferenceValueProviderService_DeleteReferenceValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReferenceValueDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReferenceValueProviderServiceServer).DeleteReferenceValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReferenceValueProviderService_DeleteReferenceValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReferenceValueProviderServiceServer).DeleteReferenceValue(ctx, req.(*ReferenceValueDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReferenceValueProviderService_SetReferenceValueList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReferenceValueListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReferenceValueProviderServiceServer).SetReferenceValueList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReferenceValueProviderService_SetReferenceValueList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReferenceValueProviderServiceServer).SetReferenceValueList(ctx, req.(*ReferenceValueListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReferenceValueProviderService_ServiceDesc is the grpc.ServiceDesc for ReferenceValueProviderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReferenceValueProviderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "reference.ReferenceValueProviderService",
	HandlerType: (*ReferenceValueProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryReferenceValue",
			Handler:    _ReferenceValueProviderService_QueryReferenceValue_Handler,
		},
		{
			MethodName: "RegisterReferenceValue",
			Handler:    _ReferenceValueProviderService_RegisterReferenceValue_Handler,
		},
		{
			MethodName: "DeleteReferenceValue",
			Handler:    _ReferenceValueProviderService_DeleteReferenceValue_Handler,
		},
		{
			MethodName: "SetReferenceValueList",
			Handler:    _ReferenceValueProviderService_SetReferenceValueList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "reference.proto",
}
