// Copyright (c) 2026 Alibaba Cloud
//
// SPDX-License-Identifier: Apache-2.0

use log::warn;
use serde_json::Value;
use std::io::ErrorKind;
use std::path::PathBuf;

pub const DEFAULT_SIGNER_TRANSPARENCY_PATH: &str =
    "/run/trustee/attestation-service/signer/signer_transparency.json";

/// Load the optional signer transparency bundle generated by the provisioning tool.
///
/// Token issuance must continue when the bundle is not provisioned yet, so absent
/// files and malformed data are logged and treated as "no transparency claim".
pub fn load_signer_transparency() -> Option<Value> {
    let path = signer_transparency_path();
    let content = match std::fs::read_to_string(&path) {
        Ok(content) => content,
        Err(err) if err.kind() == ErrorKind::NotFound => return None,
        Err(err) => {
            warn!(
                "Failed to read signer transparency file {}: {err}",
                path.display()
            );
            return None;
        }
    };

    match serde_json::from_str(&content) {
        Ok(value) => Some(value),
        Err(err) => {
            warn!(
                "Failed to parse signer transparency file {}: {err}",
                path.display()
            );
            None
        }
    }
}

fn signer_transparency_path() -> PathBuf {
    std::env::var("AS_SIGNER_TRANSPARENCY_PATH")
        .map(PathBuf::from)
        .unwrap_or_else(|_| PathBuf::from(DEFAULT_SIGNER_TRANSPARENCY_PATH))
}
