name: Trustee Container Image Build
on:
  push:
    branches:
      - "main"
    # 所有修改默认触发此测试
    paths:
      - '**'
  pull_request:
    paths:
      - '**'
  create:

jobs:
  build-image:
    name: Build ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: gRPC AS
            dockerfile: Dockerfile.as-grpc
            image: attestation-service:latest
          - name: RESTful AS
            dockerfile: Dockerfile.as-restful
            image: attestation-service:latest
          - name: RVPS
            dockerfile: Dockerfile.rvps
            image: rvps:latest
          - name: KBS
            dockerfile: Dockerfile.kbs
            image: kbs:latest
          - name: Trustee Gateway
            dockerfile: Dockerfile.trustee-gateway
            image: trustee-gateway:latest
          - name: Trustee Frontend
            dockerfile: Dockerfile.frontend
            image: trustee-frontend:latest

    steps:
    - name: Code checkout
      uses: actions/checkout@v5

    - name: Build ${{ matrix.name }} Container Image
      run: |
        DOCKER_BUILDKIT=1 docker build -t ${{ matrix.image }} . -f ${{ matrix.dockerfile }}
